
spring:
  profiles:
    active: "@spring.active@"
  session:
    store-type: redis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 10
      max-active: 20
      # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
      keep-alive: true
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 测试连接是否可用的sql
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      # 要启用PSCache, 必须配置大于0
      max-open-prepared-statements: 40
      # Spring 监控，利用aop 对指定接口的执行时间，jdbc数进行记录
      aop-patterns: "com.springboot.template.dao.*"
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filter:
        # 开启druiddatasource的状态监控
        stat:
          enabled: true
          db-type: mysql
          # 开启慢sql监控，超过2s 就认为是慢sql，记录到日志中
          log-slow-sql: true
          slow-sql-millis: 2000
      # 配置sql监控服务
      stat-view-servlet:
        # 启用
        enabled: true
        login-username: admin
        login-password: 123456
        # 是否可以重置
        reset-enable: true
        url-pattern: /druid/*
        # 添加IP白名单
        #allow: "127.0.0.1"
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      # 配置WebStatFilter，用于采集web关联监控的数据
      web-stat-filter:
        # 启用http://localhost:8080/druid/login.html
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"


  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    database: ${spring.redis.database}
    lettuce:
      pool:
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 30000
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
    timeout: 3000
  jackson:
    # 时区
    time-zone: Asia/Shanghai
    # 地区
    locale: CHIAN
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent-output: true
      # 忽略无法转换的对象
      fail-on-empty-beans: false
    # 如何序列化
    #default-property-inclusion: non_null
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail-on-unknown-properties: false
    parser:
      # 允许出现特殊字符和转义符
      allow-unquoted-control-chars: true
      # 允许出现单引号
      allow-single-quotes: true

mybatis-plus:
  type-aliases-package: com.sike.mall.user.entity
  global-config:
    # 是否打印mybatis-plus的log
    banner: false
    db-config:
      # id类型
      id-type: auto
      # 已删除
      logic-delete-value: 1
      # 未删除
      logic-not-delete-value: 0
  mapper-locations:
    - classpath*:com/sike/mall/user/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl