server:
  port: 8030


#spring:
#  rabbitmq:
#    host:
#    port:
#    username: guest
#    password: guest
    # 超时时间
    #connection-timeout: 5000
    # 消息确认模式
    #publisher-confirm-type: correlated
    # 消息送达模式
    #publisher-returns: true
    # 不可达消息不会被broker删除
    #template:
    #  mandatory: true
