
server:
  port: 8025

spring:
  session:
    store-type: redis

feign:
  httpclient:
    enabled: true
  hystrix:
    # 服务降级
    enabled: true
  # 开启openFeign对sentinel的整合
  sentinel:
    enabled: true

ribbon:
  eager-load:
    # Ribbon选用饥饿加载模式eager-load
    enabled: true
    clients: phoenix-provider

logging:
  level:
    com.echo.mall.test.service: error