server:
  port: 8010
logging:
  level:
    com.sike.mall.user.mapper: debug

spring:
  session:
    store-type: redis


mybatis-plus:
  type-aliases-package: com.sike.mall.user.entity
  mapper-locations:
    - classpath*:com/sike/mall/user/**/*.xml