server:
  port: 8011
logging:
  level:
    com.echo.mall.user.mapper: debug

spring:
  session:
    store-type: redis


mybatis-plus:
  type-aliases-package: com.echo.mall.user.entity
  mapper-locations:
    - classpath*:com/echo/mall/user/**/*.xml