server:
  port: 8040

logging:
  level:
    com.echo.mall.order.mapper: debug
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 以下配置可去掉
feign:
  httpclient:
    enabled: true
  hystrix:
    # 服务降级
    enabled: true

ribbon:
  eager-load:
    # Ribbon选用饥饿加载模式eager-load
    enabled: true
    clients: phoenix-provider